### ISSUE TITLE
Would this dataset provide recognition label

### ISSUE THREAD

**Issue by vc384** [chongshengzhang/shopsign#2]
Your paper said this dataset can be used in both detection and recognition tasks. After I scaned your paper, I only find the experiments on detection methonds, excuding recognition method, such as CRNN or Aster. Does this mean this dataset would not provide recognition label?

**Comment by chongshengzhang** [comment]
Thanks for your questions.  Our dataset has annotation labels.  It should be mentioned that, the recognition  results on our dataset will be updated later in the revised arxiv paper.   In short, we have annotation labels. But you need to wait a few weeks to have access to the full dataset.

**Comment by vc384** [comment]
Good work! Thanks for your reply.
